version: '3.8'

services:
  astreinte-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astreinte-app
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Volume pour persister les logs Nginx (optionnel)
      - ./logs:/var/log/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astreinte.rule=Host(`astreinte.localhost`)"
      - "traefik.http.services.astreinte.loadbalancer.server.port=80"
    networks:
      - astreinte-network

networks:
  astreinte-network:
    driver: bridge